name: Prologcoin Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - name: boost
      run: brew install boost
    - name: libsecp
      run: git clone https://github.com/datavetaren/secp256k1-zkp ../secp256k1-zkp
    - name: doall
      run: make all
    - name: zip
      run: cd bin && zip -r prologcoin_macosx.zip prologcoind prologcoin-data
    - name: release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: upload
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: bin/prologcoin_macosx.zip
        asset_name: prologcoin_macosx.zip
        asset_content_type: application/zip
